# Generated by Django 4.2.2 on 2023-06-18 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_paciente_medico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='especialidad',
        ),
    ]
