# Generated by Django 4.2.2 on 2023-06-18 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_remove_paciente_especialidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='medico',
        ),
        migrations.AddField(
            model_name='especialidad',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientes.medico'),
        ),
        migrations.AddField(
            model_name='medico',
            name='apellido',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='especialidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientes.especialidad'),
        ),
    ]
