# Generated by Django 4.2.2 on 2023-07-07 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_remove_medico_especialidad_remove_paciente_medico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sangre', models.CharField(max_length=20, null=True)),
                ('alergias', models.CharField(max_length=50, null=True)),
                ('enfermedade_heriditarias', models.CharField(max_length=50, null=True)),
                ('tabaco', models.CharField(max_length=20, null=True)),
                ('alcohol', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='expediente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientes.expediente'),
        ),
    ]
