# Generated by Django 4.2.2 on 2023-07-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0008_expediente_paciente_expediente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='tipo_sangre',
            field=models.CharField(choices=[('0+', 'O positivo'), ('0-', 'O negativ'), ('A+', 'A positivo'), ('A-', 'A negativo'), ('B+', 'B positivo'), ('B-', 'B negativo')], max_length=2, null=True),
        ),
    ]
